# serverless.yml

service: memories-backend

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-2

plugins:
  - serverless-offline

functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'